### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by awais-amjed** [awais-amjed/recipe-app#8]
## Project [link](https://github.com/awais-amjed/recipe-app/projects/1)
# There are 2 people in our team.

- Team Member 1: [Roshan Bajgain](https://github.com/roshan-bajgain)
- Team Member 2: [Awais Amjed](https://github.com/awais-amjed)

**Comment by Whoistolu** [comment]
### Hi Team
@awais-amjed and @roshan-bajgain 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
